// Run: node fill_sessions.js
// Fills all remaining empty sessions in data.js with real MCQ content
const fs = require('fs');
const path = require('path');

const dataFile = path.join(__dirname, 'data.js');
let content = fs.readFileSync(dataFile, 'utf8');

// Generic question builder for a subject
function q(id, text, options, correct, explanation) {
    return { id, text, options, correct, explanation };
}

// Build sessions array string from 50 questions
function sessions(qs) {
    const arr = [];
    for (let i = 0; i < 5; i++) {
        arr.push({
            id: i + 1,
            name: `Session ${i + 1}`,
            questions: qs.slice(i * 10, i * 10 + 10)
        });
    }
    return JSON.stringify(arr);
}

// Replace empty sessions for a subject by id
function patch(subjectId, qs) {
    const placeholder = `id: "${subjectId}",`;
    const idx = content.indexOf(placeholder);
    if (idx === -1) { console.log('NOT FOUND:', subjectId); return; }
    const emptyIdx = content.indexOf('sessions: []', idx);
    if (emptyIdx === -1) { console.log('Already filled:', subjectId); return; }
    const replacement = `sessions: ${sessions(qs)}`;
    content = content.slice(0, emptyIdx) + replacement + content.slice(emptyIdx + 'sessions: []'.length);
    console.log('Patched:', subjectId);
}

// ── CS504 - Software Engineering I ──────────────────────────────────────────
patch('cs504', [
q(1,'What is software engineering?',['Writing code only','The systematic application of engineering principles to software development','A type of programming','A type of computer science'],1,'Software engineering applies engineering principles to the design, development, testing, and maintenance of software systems.'),
q(2,'What is the SDLC?',['Software Development Life Cycle — the process of planning, creating, testing, and deploying software','A type of programming language','A type of database','A type of network'],0,'The SDLC defines the phases of software development: requirements, design, implementation, testing, deployment, and maintenance.'),
q(3,'What is the waterfall model?',['A model with waterfalls','A sequential SDLC model where each phase must be completed before the next begins','An agile model','An iterative model'],1,'The waterfall model is a linear, sequential approach where each phase (requirements, design, coding, testing, deployment) must be completed before the next.'),
q(4,'What is the agile methodology?',['A fast methodology','An iterative, incremental approach to software development emphasizing flexibility and customer collaboration','A waterfall variant','A type of SDLC'],1,'Agile delivers software in short iterations (sprints), emphasizing customer collaboration, responding to change, and working software over documentation.'),
q(5,'What is Scrum?',['A rugby term','An agile framework using sprints, daily standups, and defined roles (Scrum Master, Product Owner, Team)','A type of waterfall','A type of SDLC'],1,'Scrum is an agile framework with time-boxed sprints (2-4 weeks), daily standups, sprint planning, and retrospectives.'),
q(6,'What is a use case?',['A case study','A description of how a user interacts with a system to achieve a specific goal','A type of requirement','A type of test case'],1,'A use case describes a sequence of interactions between a user (actor) and a system to accomplish a specific goal.'),
q(7,'What is requirements engineering?',['Writing requirements','The process of eliciting, analyzing, documenting, and validating software requirements','A type of design','A type of testing'],1,'Requirements engineering systematically identifies, documents, and validates what a software system must do (functional) and how it must perform (non-functional).'),
q(8,'What is a functional requirement?',['A requirement that functions','A requirement specifying what the system should do — its features and behaviors','A non-functional requirement','A type of use case'],1,'Functional requirements define specific behaviors or functions of the system (e.g., the system shall allow users to log in with username and password).'),
q(9,'What is a non-functional requirement?',['A requirement that does not function','A requirement specifying how the system performs — quality attributes like performance, security, usability','A functional requirement','A type of use case'],1,'Non-functional requirements define quality attributes: performance (response time), security, reliability, scalability, and usability.'),
q(10,'What is software design?',['Designing software visually','The process of defining the architecture, components, interfaces, and data for a system','A type of coding','A type of testing'],1,'Software design translates requirements into a blueprint for the system, defining architecture, modules, interfaces, and data structures.'),
q(11,'What is UML?',['Unified Modeling Language — a standard notation for visualizing software design','Universal Machine Language','Unified Machine Logic','A type of programming language'],0,'UML is a standardized visual language for modeling software systems using diagrams (class, sequence, use case, activity diagrams).'),
q(12,'What is a class diagram?',['A diagram of classes','A UML diagram showing classes, their attributes, methods, and relationships','A type of sequence diagram','A type of use case diagram'],1,'A class diagram shows the static structure of a system — classes, their attributes and methods, and relationships (inheritance, association, composition).'),
q(13,'What is cohesion in software design?',['How things stick together','The degree to which elements within a module belong together and serve a single purpose','A type of coupling','A design principle'],1,'High cohesion means a module has a single, well-defined purpose. High cohesion is desirable as it makes modules easier to understand and maintain.'),
q(14,'What is coupling in software design?',['Connecting modules','The degree of interdependence between software modules','A type of cohesion','A design principle'],1,'Coupling measures how much modules depend on each other. Low coupling is desirable — changes in one module should minimally affect others.'),
q(15,'What is the DRY principle?',['Do not Repeat Yourself — avoid code duplication','Do Repeat Yourself','A type of design pattern','A type of coding standard'],0,'DRY (Do not Repeat Yourself) states that every piece of knowledge should have a single, unambiguous representation in the system.'),
q(16,'What is a design pattern?',['A visual pattern','A reusable solution to a commonly occurring problem in software design','A type of algorithm','A type of architecture'],1,'Design patterns are proven, reusable solutions to common software design problems (e.g., Singleton, Factory, Observer, MVC).'),
q(17,'What is the MVC pattern?',['Model-View-Controller — separates application into data, UI, and logic','Multiple View Controller','A type of design pattern','A type of architecture'],0,'MVC separates an application into Model (data), View (UI), and Controller (logic), improving organization and testability.'),
q(18,'What is software testing?',['Testing software manually','The process of evaluating software to find defects and verify it meets requirements','A type of debugging','A type of quality assurance'],1,'Software testing evaluates software to identify defects, verify functionality, and ensure the system meets specified requirements.'),
q(19,'What is unit testing?',['Testing one unit','Testing individual components or functions in isolation to verify they work correctly','A type of integration testing','A type of system testing'],1,'Unit testing tests individual functions or components in isolation, typically written by developers using frameworks like JUnit or pytest.'),
q(20,'What is integration testing?',['Testing integration','Testing how multiple components work together as a group','A type of unit testing','A type of system testing'],1,'Integration testing verifies that multiple components or modules work correctly when combined together.'),
q(21,'What is system testing?',['Testing the whole system','Testing the complete, integrated system against specified requirements','A type of integration testing','A type of acceptance testing'],1,'System testing tests the complete, integrated system to verify it meets all specified functional and non-functional requirements.'),
q(22,'What is acceptance testing?',['Accepting the software','Testing conducted by end users to verify the system meets their needs before acceptance','A type of system testing','A type of unit testing'],1,'Acceptance testing (UAT) is performed by end users to verify the system meets their business requirements before final acceptance.'),
q(23,'What is regression testing?',['Testing regressions','Re-testing previously working functionality after changes to ensure nothing is broken','A type of unit testing','A type of system testing'],1,'Regression testing re-runs existing tests after code changes to ensure that new changes have not broken previously working functionality.'),
q(24,'What is a software bug?',['An insect in the computer','A defect or error in software that causes it to produce incorrect or unexpected results','A type of error','A type of exception'],1,'A software bug is a defect, flaw, or error in code that causes the software to behave incorrectly or produce unexpected results.'),
q(25,'What is debugging?',['Finding bugs','The process of identifying, locating, and fixing bugs in software','A type of testing','A type of code review'],1,'Debugging is the process of finding the root cause of a bug and fixing it to restore correct behavior.'),
q(26,'What is version control?',['Controlling versions','A system tracking changes to source code over time, enabling collaboration and rollback','A type of software tool','A type of project management'],1,'Version control (e.g., Git) tracks changes to source code, enabling multiple developers to collaborate and revert to previous versions.'),
q(27,'What is software maintenance?',['Maintaining software physically','Modifying software after delivery to correct faults, improve performance, or adapt to new requirements','A type of testing','A type of development'],1,'Software maintenance involves modifying software after deployment to fix bugs, improve performance, or adapt to changing requirements.'),
q(28,'What is technical debt?',['Debt from technology purchases','The implied cost of future rework caused by choosing quick, easy solutions over better approaches','A type of software quality','A type of project management'],1,'Technical debt accumulates when developers take shortcuts that work now but create problems later, requiring future rework.'),
q(29,'What is code review?',['Reviewing code visually','A systematic examination of source code by peers to find defects and improve quality','A type of testing','A type of debugging'],1,'Code review is a peer examination of source code to identify bugs, improve quality, share knowledge, and ensure coding standards.'),
q(30,'What is continuous integration (CI)?',['Integrating continuously','The practice of frequently merging code changes and automatically building and testing the software','A type of DevOps','A type of agile'],1,'CI automatically builds and tests code whenever developers commit changes, detecting integration issues early.'),
q(31,'What is a software architecture?',['The physical structure of software','The high-level structure of a software system defining its components and their relationships','A type of design','A type of pattern'],1,'Software architecture defines the high-level structure of a system — its components, their responsibilities, and how they interact.'),
q(32,'What is a microservices architecture?',['Small services','An architectural style structuring an application as small, independently deployable services','A monolithic architecture','A type of SOA'],1,'Microservices architecture decomposes an application into small, independent services that communicate via APIs, enabling independent deployment.'),
q(33,'What is a monolithic architecture?',['A large architecture','An architecture where all components are tightly coupled in a single deployable unit','A microservices architecture','A type of SOA'],1,'A monolithic architecture packages all application components (UI, business logic, data access) into a single deployable unit.'),
q(34,'What is software quality?',['Good software','The degree to which software meets specified requirements and satisfies user needs','A type of testing','A type of design'],1,'Software quality encompasses correctness, reliability, efficiency, maintainability, portability, and usability.'),
q(35,'What is the ISO/IEC 25010 quality model?',['A quality standard','A standard defining software quality characteristics including functionality, reliability, usability, efficiency, maintainability, portability','A type of testing standard','A type of process standard'],1,'ISO/IEC 25010 defines software product quality characteristics: functional suitability, reliability, performance efficiency, usability, security, maintainability, and portability.'),
q(36,'What is a software prototype?',['A prototype of software','An early working model of a system used to explore requirements and design','A type of software','A type of testing'],1,'A prototype is an early, incomplete version of a system used to explore requirements, test design ideas, and get user feedback.'),
q(37,'What is risk management in software projects?',['Managing risks','Identifying, analyzing, and mitigating risks that could affect project success','A type of project management','A type of quality management'],1,'Risk management identifies potential problems (technical, schedule, resource risks), assesses their likelihood and impact, and plans mitigation strategies.'),
q(38,'What is a software project plan?',['A plan for software','A document defining project scope, schedule, resources, and milestones','A type of requirements document','A type of design document'],1,'A software project plan defines the scope, schedule, resources, milestones, and risk management approach for a software project.'),
q(39,'What is the spiral model?',['A spiral-shaped model','An iterative SDLC model combining waterfall and prototyping with risk analysis at each iteration','A type of waterfall','A type of agile'],1,'The spiral model iterates through planning, risk analysis, engineering, and evaluation phases, making it suitable for large, high-risk projects.'),
q(40,'What is extreme programming (XP)?',['Extreme coding','An agile methodology emphasizing pair programming, test-driven development, and continuous feedback','A type of Scrum','A type of waterfall'],1,'XP is an agile methodology with practices like pair programming, TDD, continuous integration, small releases, and customer involvement.'),
q(41,'What is test-driven development (TDD)?',['Testing before development','Writing tests before writing the code, then writing code to pass the tests','A type of testing','A type of agile'],1,'TDD writes failing tests first, then writes the minimum code to pass them, then refactors — Red, Green, Refactor cycle.'),
q(42,'What is pair programming?',['Two programmers on one computer','Two developers working together at one workstation — one writes code, the other reviews','A type of code review','A type of agile practice'],1,'Pair programming has two developers working together: the driver writes code while the navigator reviews and thinks strategically.'),
q(43,'What is a sprint in Scrum?',['A fast run','A time-boxed iteration (typically 2-4 weeks) in which a Scrum team completes a set of work','A type of agile','A type of project phase'],1,'A sprint is a fixed-length iteration (2-4 weeks) in Scrum during which the team completes a set of user stories from the product backlog.'),
q(44,'What is a product backlog?',['A list of products','A prioritized list of features, requirements, and improvements for a software product','A type of sprint','A type of Scrum artifact'],1,'The product backlog is a prioritized list of all desired features and requirements for the product, maintained by the Product Owner.'),
q(45,'What is a user story?',['A story about users','A short description of a feature from the user\'s perspective: As a [user], I want [goal] so that [benefit]','A type of use case','A type of requirement'],1,'A user story describes a feature from the user\'s perspective: "As a [type of user], I want [goal] so that [benefit]."'),
q(46,'What is refactoring?',['Rebuilding software','Restructuring existing code without changing its external behavior to improve readability and maintainability','A type of debugging','A type of testing'],1,'Refactoring improves the internal structure of code (naming, removing duplication, simplifying logic) without changing its observable behavior.'),
q(47,'What is software configuration management (SCM)?',['Managing software configurations','The discipline of tracking and controlling changes to software throughout its lifecycle','A type of version control','A type of project management'],1,'SCM tracks and controls changes to software artifacts (code, documents, configurations) to maintain integrity and traceability.'),
q(48,'What is a baseline in software engineering?',['A base line','A formally reviewed and agreed-upon specification that serves as the basis for further development','A type of version','A type of configuration'],1,'A baseline is a formally approved version of a software artifact that can only be changed through formal change control procedures.'),
q(49,'What is software reuse?',['Reusing software','Using existing software components, libraries, or frameworks in new systems to reduce development effort','A type of design pattern','A type of software engineering'],1,'Software reuse leverages existing components, libraries, frameworks, or patterns to reduce development time, cost, and risk.'),
q(50,'What is the V-model in software development?',['A V-shaped model','An SDLC model where each development phase has a corresponding testing phase','A type of waterfall','A type of agile'],1,'The V-model pairs each development phase with a corresponding testing phase: requirements↔acceptance testing, design↔integration testing, coding↔unit testing.')
]);
